apiVersion: skaffold/v4beta4
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
metadata:
  name: client-svc
build:
  artifacts:
    - image: jzenon/client
      context: .
      sync:
        manual:
          - src: .
            dest: .
      docker:
        dockerfile: Dockerfile
portForward:
  - resourceType: service
    resourceName: client-svc
    port: 3000
