apiVersion: apps/v1
kind: Deployment
metadata:
  name: soccerfootballstuff-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soccerfootballstuff-client
  template:
    metadata:
      labels:
        app: soccerfootballstuff-client
    spec:
      containers:
        - name: soccerfootballstuff-client
          image: jzenon13/soccerfootballstuff-client
          resources:
            requests:
              memory: "300Mi"
              cpu: "500m"
            limits:
              memory: "600Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: soccerfootballstuff-client-svc
spec:
  selector:
    app: soccerfootballstuff-client
  ports:
    - name: soccerfootballstuff-client
      protocol: TCP
      port: 3000
      targetPort: 3000
